// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestfirstTest {
    private WebDriver driver;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", ".\\chromedriver_win32\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        Map<String, Object> vars = new HashMap<>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testfirst() {
        driver.get("https://comfy.ua/ua/");
        driver.manage().window().setSize(new Dimension(1024, 540));
        driver.findElement(By.cssSelector("#menuContainer > #menuLink .header-menu__icon-line")).click();
        driver.findElement(By.cssSelector(".sidebar-nav__item:nth-child(1) .sidebar-nav__title")).click();
        driver.findElement(By.cssSelector("#menuCategory2 .main-menu-list__name")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#menuSubCategory2 > .submenu-list__item:nth-child(1) .submenu-list__overview"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("#menuSubCategory2 > .submenu-list__item:nth-child(1) .submenu-list__overview")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.linkText("Системні блоки (ПК)")).click();
        driver.findElement(By.cssSelector(".category-view-switcher-mobile__item")).click();
        driver.findElement(By.cssSelector(".category-controls-mobile__filter")).click();
        driver.findElement(By.cssSelector(".d-bs__wrapper #label_actions .filter__item-wrapper-content")).click();
        driver.close();
    }
}
